services:
  api1:
    image: thetonbr/rinha-zig-2026:v13
    environment:
      LISTEN_SOCKET_PATH: /sockets/api1.sock
    volumes:
      - sockets:/sockets:rw
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150M"
    networks:
      - rinha-net

  api2:
    image: thetonbr/rinha-zig-2026:v13
    environment:
      LISTEN_SOCKET_PATH: /sockets/api2.sock
    volumes:
      - sockets:/sockets:rw
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150M"
    networks:
      - rinha-net

  lb:
    image: haproxy:2.9-alpine
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets:rw
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50M"
    networks:
      - rinha-net

volumes:
  sockets:

networks:
  rinha-net:
    driver: bridge
